name: mallofpakistan
favicon: null
layout_spectrum: 0.16367
typography_spectrum: 0.49167
title: 'Mall of Pakistan - Ab Khareedo Global!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#4bbb7a'
    - '#fffbfe'
    - '#45bc79'
    - '#46bb7d'
  brandStrength: 0.75
  lightness: 0.2750456724315882
  saturation: 0.18466608552262187
  rhythmicContrast: 0.5291006132028997
purpose: []
